version: "3"
services:
    web:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/home/node/src
            - /home/node/src/node-modules
        links:
            - db
        environment:
            MONGO_CONNECTION_STRING: mongodb://db:27017
    db:
        image: mongo:3
        